portfolio/accounts/urls.py
from django.urls import path

from .views import Login, Register, Logout

app_name = 'accounts'

urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

portfolio/core/urls.py
from django.urls import path

from .views import AdminPanel, Home

app_name = 'core'

urlpatterns = [
    path('admin-panel/', AdminPanel.as_view(), name='admin-panel'),
    path('', Home.as_view(), name='home'),
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

portfolio/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    image = models.ImageField(default='1.jpg')

    class Meta:
        verbose_name = 'User'


@receiver(post_save, sender=User)
def insert_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class Profile(models.Model):
    user = models.OneToOneField('User', models.CASCADE)
    job_title = models.CharField(max_length=155, verbose_name="Job title", blank=True, default='')

    def __str__(self):
        return self.user.username

portfolio/core/models.py
from django.db import models

# Create your models here.

portfolio/accounts/forms/login.py
from django import forms


class LoginForm(forms.Form):
    required_css_class = 'fv-row orm-label fw-bolder text-dark fs-6'
    attrs = {
        'class': 'form-control form-control-lg form-control-solid'
    }
    username = forms.CharField(label='نام کاربری', widget=forms.TextInput(attrs=attrs))
    password = forms.CharField(label='کلمه عبور', widget=forms.PasswordInput(attrs=attrs))

portfolio/accounts/forms/register.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class RegisterForm(forms.ModelForm):
    required_css_class = 'fv-row orm-label fw-bolder text-dark fs-6'
    job_title = forms.CharField(label='عنوان شغلی')
    password = forms.CharField(widget=forms.PasswordInput(), label='کلمه عبور')
    password_confirm = forms.CharField(widget=forms.PasswordInput(), label='تایید کلمه عبور')

    class Meta:
        model = User
        fields = ('username', 'email', 'job_title', 'password', 'password_confirm',)
        labels = {
            'username': 'نام کاربری',
            'email': 'پست الکترونیک',
            'job_title': 'عنوان شغلی',
            'password': 'کلمه عبور',
            'password_confirm': 'تایید کلمه عبور',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({
                'class': 'form-control form-control-lg form-control-solid'
            })
            field.help_text = ""

    def clean(self):
        if self.cleaned_data['password'] != self.cleaned_data['password_confirm']:
            raise forms.ValidationError("کلمه عبور و تایید کلمه عبور یکسان نمی باشد")

        return self.cleaned_data

portfolio/accounts/views/login.py
from django.contrib import messages
from django.contrib.auth import get_user_model, login, authenticate
from django.shortcuts import render, redirect
from django.views import View

from ..forms.login import LoginForm

User = get_user_model()


class Login(View):
    template_name = './accounts/login.html'
    form = LoginForm

    def get(self, request):
        return render(request, self.template_name, {'form': self.form})

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            username = clean_data['username']
            password = clean_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('core:home')
            messages.error(request, 'نام کاربری یا کلمه عبور صحیح نمی باشد', 'danger')
        return render(request, self.template_name, {'form': self.form})

portfolio/accounts/views/logout.py
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views import View


class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('core:home')

portfolio/accounts/views/register.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.views import View

from ..forms.register import RegisterForm

User = get_user_model()


class Register(View):
    template_name = './accounts/register.html'
    form = RegisterForm

    def get(self, request):
        return render(
            request,
            self.template_name,
            {
                'form': self.form
            }
        )

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            User.objects.create_user(
                clean_data['username'],
                clean_data['email'],
                clean_data['password'],
            )
            return redirect('core:home')

        return render(
            request,
            self.template_name,
            {
                'form': form
            }
        )

portfolio/core/views.py
from django.shortcuts import render
from django.views import View


class AdminPanel(View):
    def get(self, request):
        if request.user.is_authenticated and hasattr(request.user, 'profile'):
            profile = request.user.profile
        else:
            profile = None
        return render(request, 'core/admin-panel.html', {'profile': profile})


class Home(View):
    def get(self, request):
        if request.user.is_authenticated and hasattr(request.user, 'profile'):
            profile = request.user.profile
        else:
            profile = None
        return render(request, 'core/home.html', {'profile': profile})

portfolio/accounts/templates/accounts/login.html
{% extends 'authenticate-base.html' %}
{% load static %}

{% block content %}

    <div class="w-lg-600px bg-body rounded shadow-sm p-10 p-lg-15 mx-auto">
        <form class="form w-100" novalidate="novalidate" id="kt_sign_up_form" method="Post">
            {% csrf_token %}
            <div class="mb-10 text-center">
                <h1 class="text-dark mb-3">ورود</h1>
                <div class="text-gray-400 fw-bold fs-4">کلمه عبور خود را فراموش کرده اید؟
                    <a href="{% url 'accounts:login' %}"
                       class="link-primary fw-bolder">بازنشانی کلمه عبور</a></div>
            </div>
            {{ form.as_p }}
            {% include 'messages.html' %}
            <div class="text-center">
                <input type="submit" class="btn btn-lg btn-primary" value="ورود"/>
            </div>
        </form>
    </div>



{% endblock %}

portfolio/accounts/templates/accounts/register.html
{% extends 'authenticate-base.html' %}
{% load static %}

{% block content %}

    <div class="w-lg-600px bg-body rounded shadow-sm p-10 p-lg-15 mx-auto">
        <form class="form w-100" novalidate="novalidate" id="kt_sign_up_form" method="Post">
            {% csrf_token %}
            <div class="mb-10 text-center">
                <h1 class="text-dark mb-3">ساختن اکانت</h1>
                <div class="text-gray-400 fw-bold fs-4">اکانت کاربری دارید؟
                    <a href="{% url 'accounts:login' %}"
                       class="link-primary fw-bolder">ورود</a></div>
            </div>
            {{ form.as_p }}
            <div class="text-center">
                <input type="submit" class="btn btn-lg btn-primary" value="ثبت"/>
            </div>
        </form>
    </div>



{% endblock %}

portfolio/core/templates/core/admin-panel.html
{% extends 'base.html' %}
{% block title %}
    داشبورد
{% endblock %}
{% block subtitle %}
    زیر شاخه
{% endblock %}
{% block content %}
    <h3> Hi Mohammad</h3>
{% endblock %}

portfolio/core/templates/core/home.html
{% extends 'base.html' %}
{% block title %}
    داشبورد
{% endblock %}
{% block subtitle %}
    زیر شاخه
{% endblock %}
{% block content %}
    <h3> Hi Mohammad</h3>
{% endblock %}

portfolio/templates/authenticate-base.html
{% load static %}
<!DOCTYPE html>
<!--
نویسنده: ساتراس وب
محصولات نام: مترونیک - Bootstrap 5 HTML, VueJS, React, Angular & Laravel Admin داشبورد Theme
خرید: https://1.envato.market/EA4JP
وب سایت: http://www.keenthemes.com
تماس با ما: support@keenthemes.com
دنبال کردن: www.twitter.com/keenthemes
دریبل: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
لاینسس شده: For each use you must have a valid license purchased only from above link in order to legally use the theme for your project.
-->
<html direction="rtl" dir="rtl" style="direction: rtl">
<!--begin::Head-->
<head>
    <base href="../../../">
    <title>رزومه ساز</title>
    <meta charset="utf-8"/>
    <meta name="description"
          content=" رزومه ساز برای برنامه نویسان"/>
    <meta name="keywords"
          content="مترونیک, bootstrap, bootstrap 5, Angular, VueJs, React, Laravel, admin themes, web design, figma, web development, free templates, free admin themes, bootstrap theme, bootstrap template, bootstrap dashboard, bootstrap dak mode, bootstrap button, bootstrap datepicker, bootstrap timepicker, fullcalendar, datatables, flaticon"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta property="og:locale" content="en_US"/>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="رزومه ساز"/>
    <meta property="og:url" content="https://keenthemes.com/metronic"/>
    <meta property="og:site_name" content="mrprocs | sepydev"/>
    {#    <link rel="canonical" href="Https://preview.keenthemes.com/metronic8"/>#}
    <link rel="shortcut icon" href="{% static 'assets/media/logos/favicon.ico' %}"/>
    <!--begin::Fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700"/>
    <!--end::Fonts-->
    <!--begin::Global Stylesheets Bundle(used by all pages)-->
    <link href="{% static 'assets/plugins/global/plugins.bundle.rtl.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/style.bundle.rtl.css' %}" rel="stylesheet" type="text/css"/>
    <!--end::Global Stylesheets Bundle-->
</head>
<!--end::Head-->
<!--begin::Body-->
<body id="kt_body" class="bg-body">
<!--begin::Main-->
<!--begin::Root-->
<div class="d-flex flex-column flex-root">

    <!--begin::احراز هویت - ثبت نام -->
    <div class="d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed"
         style="background-image: url({% static 'assets/media/illustrations/dozzy-1/14.png' %}">
        <!--begin::Content-->
        <div class="d-flex flex-center flex-column flex-column-fluid p-10 pb-lg-20">
            <!--begin::Logo-->
            <a href="{% url 'core:home' %}" class="mb-12">
                <img alt="Logo" src="{% static 'assets/media/logos/logo-1.svg' %}" class="h-40px"/>
            </a>

            {% block content %}{% endblock %}

        </div>
        <div class="d-flex flex-center flex-column-auto p-10">
            <!--begin::Links-->
            <div class="d-flex align-items-center fw-bold fs-6">
                <a href="https://keenthemes.com" class="text-muted text-hover-primary px-2">درباره ی ما</a>
                <a href="mailto:mrprocs@gmail.com" class="text-muted text-hover-primary px-2">تماس با ما</a>

            </div>
            <!--end::Links-->
        </div>

    </div>




</div>


<script>var hostUrl = "{% static 'assets' %}/";</script>
<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
</body>
</html>

portfolio/templates/footer.html
{% load static %}

<!--begin::Footer-->
<div class="footer py-4 d-flex flex-lg-column" id="kt_footer">
    <!--begin::Container-->
    <div class="container-fluid d-flex flex-column flex-md-row flex-stack">
        <!--begin::Copyright-->
        <div class="text-dark order-2 order-md-1">
            <span class="text-gray-400 fw-bold me-1">ایجاد توسط</span>
            <a href="https://keenthemes.com" target="_blank" class="text-muted text-hover-primary fw-bold me-2 fs-6">ساتراس وب</a>
        </div>
        <!--end::Copyright-->
        <!--begin::Menu-->
        <ul class="menu menu-gray-600 menu-hover-primary fw-bold order-1">
            <li class="menu-item">
                <a href="https://keenthemes.com" target="_blank" class="menu-link px-2">درباره ی ما</a>
            </li>
            <li class="menu-item">
                <a href="https://rtl-theme.com" target="_blank" class="menu-link px-2">پشتیبانی</a>
            </li>
            <li class="menu-item">
                <a href="https://www.rtl-theme.com/metronic-admin-html-template/" target="_blank" class="menu-link px-2">خرید</a>
            </li>
        </ul>
        <!--end::Menu-->
    </div>
    <!--end::Container-->
</div>
<!--end::Footer-->

portfolio/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="badge badge-light-{{ message.tags }} fs-7 fw-bolder" >{{ message }}</p>
    {% endfor %}
{% endif %}